// Code generated by protoc-gen-go.
// source: context.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	context.proto

It has these top-level messages:
	Empty
	Team
	Player
	Game
	Stat
	SavedTeam
	SavedPlayer
	SavedGame
	SavedStat
	SeasonUpdates
	FullContext
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Team struct {
	Lcsid  int32  `protobuf:"varint,2,opt,name=lcsid" json:"lcsid,omitempty"`
	Riotid int32  `protobuf:"varint,3,opt,name=riotid" json:"riotid,omitempty"`
	Name   string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Tag    string `protobuf:"bytes,5,opt,name=tag" json:"tag,omitempty"`
}

func (m *Team) Reset()                    { *m = Team{} }
func (m *Team) String() string            { return proto1.CompactTextString(m) }
func (*Team) ProtoMessage()               {}
func (*Team) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Player struct {
	Lcsid    int32    `protobuf:"varint,2,opt,name=lcsid" json:"lcsid,omitempty"`
	Riotid   int32    `protobuf:"varint,3,opt,name=riotid" json:"riotid,omitempty"`
	Name     string   `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Teamid   int32    `protobuf:"varint,5,opt,name=teamid" json:"teamid,omitempty"`
	Position string   `protobuf:"bytes,6,opt,name=position" json:"position,omitempty"`
	Addlpos  []string `protobuf:"bytes,7,rep,name=addlpos" json:"addlpos,omitempty"`
}

func (m *Player) Reset()                    { *m = Player{} }
func (m *Player) String() string            { return proto1.CompactTextString(m) }
func (*Player) ProtoMessage()               {}
func (*Player) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Game struct {
	Lcsid       int32  `protobuf:"varint,2,opt,name=lcsid" json:"lcsid,omitempty"`
	Riotgameid  string `protobuf:"bytes,3,opt,name=riotgameid" json:"riotgameid,omitempty"`
	Riotmatchid string `protobuf:"bytes,4,opt,name=riotmatchid" json:"riotmatchid,omitempty"`
	Redteamid   int32  `protobuf:"varint,5,opt,name=redteamid" json:"redteamid,omitempty"`
	Blueteamid  int32  `protobuf:"varint,6,opt,name=blueteamid" json:"blueteamid,omitempty"`
	Gamestart   int64  `protobuf:"varint,7,opt,name=gamestart" json:"gamestart,omitempty"`
	Gameend     int64  `protobuf:"varint,8,opt,name=gameend" json:"gameend,omitempty"`
}

func (m *Game) Reset()                    { *m = Game{} }
func (m *Game) String() string            { return proto1.CompactTextString(m) }
func (*Game) ProtoMessage()               {}
func (*Game) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Stat struct {
	Riotname string `protobuf:"bytes,2,opt,name=riotname" json:"riotname,omitempty"`
}

func (m *Stat) Reset()                    { *m = Stat{} }
func (m *Stat) String() string            { return proto1.CompactTextString(m) }
func (*Stat) ProtoMessage()               {}
func (*Stat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SavedTeam struct {
	Team   *Team `protobuf:"bytes,1,opt,name=team" json:"team,omitempty"`
	Teamid int32 `protobuf:"varint,2,opt,name=teamid" json:"teamid,omitempty"`
}

func (m *SavedTeam) Reset()                    { *m = SavedTeam{} }
func (m *SavedTeam) String() string            { return proto1.CompactTextString(m) }
func (*SavedTeam) ProtoMessage()               {}
func (*SavedTeam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SavedTeam) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

type SavedPlayer struct {
	Player   *Player `protobuf:"bytes,1,opt,name=player" json:"player,omitempty"`
	Playerid int32   `protobuf:"varint,2,opt,name=playerid" json:"playerid,omitempty"`
}

func (m *SavedPlayer) Reset()                    { *m = SavedPlayer{} }
func (m *SavedPlayer) String() string            { return proto1.CompactTextString(m) }
func (*SavedPlayer) ProtoMessage()               {}
func (*SavedPlayer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SavedPlayer) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type SavedGame struct {
	Game   *Game `protobuf:"bytes,1,opt,name=game" json:"game,omitempty"`
	Gameid int32 `protobuf:"varint,2,opt,name=gameid" json:"gameid,omitempty"`
}

func (m *SavedGame) Reset()                    { *m = SavedGame{} }
func (m *SavedGame) String() string            { return proto1.CompactTextString(m) }
func (*SavedGame) ProtoMessage()               {}
func (*SavedGame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SavedGame) GetGame() *Game {
	if m != nil {
		return m.Game
	}
	return nil
}

type SavedStat struct {
	Stat   *Stat `protobuf:"bytes,1,opt,name=stat" json:"stat,omitempty"`
	Statid int32 `protobuf:"varint,2,opt,name=statid" json:"statid,omitempty"`
}

func (m *SavedStat) Reset()                    { *m = SavedStat{} }
func (m *SavedStat) String() string            { return proto1.CompactTextString(m) }
func (*SavedStat) ProtoMessage()               {}
func (*SavedStat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SavedStat) GetStat() *Stat {
	if m != nil {
		return m.Stat
	}
	return nil
}

type SeasonUpdates struct {
	Teams   []*Team   `protobuf:"bytes,1,rep,name=teams" json:"teams,omitempty"`
	Players []*Player `protobuf:"bytes,2,rep,name=players" json:"players,omitempty"`
}

func (m *SeasonUpdates) Reset()                    { *m = SeasonUpdates{} }
func (m *SeasonUpdates) String() string            { return proto1.CompactTextString(m) }
func (*SeasonUpdates) ProtoMessage()               {}
func (*SeasonUpdates) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SeasonUpdates) GetTeams() []*Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

func (m *SeasonUpdates) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type FullContext struct {
	Teams   []*SavedTeam   `protobuf:"bytes,1,rep,name=teams" json:"teams,omitempty"`
	Players []*SavedPlayer `protobuf:"bytes,2,rep,name=players" json:"players,omitempty"`
	Games   []*SavedGame   `protobuf:"bytes,3,rep,name=games" json:"games,omitempty"`
	Stats   []*SavedStat   `protobuf:"bytes,4,rep,name=stats" json:"stats,omitempty"`
}

func (m *FullContext) Reset()                    { *m = FullContext{} }
func (m *FullContext) String() string            { return proto1.CompactTextString(m) }
func (*FullContext) ProtoMessage()               {}
func (*FullContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *FullContext) GetTeams() []*SavedTeam {
	if m != nil {
		return m.Teams
	}
	return nil
}

func (m *FullContext) GetPlayers() []*SavedPlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *FullContext) GetGames() []*SavedGame {
	if m != nil {
		return m.Games
	}
	return nil
}

func (m *FullContext) GetStats() []*SavedStat {
	if m != nil {
		return m.Stats
	}
	return nil
}

func init() {
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
	proto1.RegisterType((*Team)(nil), "proto.Team")
	proto1.RegisterType((*Player)(nil), "proto.Player")
	proto1.RegisterType((*Game)(nil), "proto.Game")
	proto1.RegisterType((*Stat)(nil), "proto.Stat")
	proto1.RegisterType((*SavedTeam)(nil), "proto.SavedTeam")
	proto1.RegisterType((*SavedPlayer)(nil), "proto.SavedPlayer")
	proto1.RegisterType((*SavedGame)(nil), "proto.SavedGame")
	proto1.RegisterType((*SavedStat)(nil), "proto.SavedStat")
	proto1.RegisterType((*SeasonUpdates)(nil), "proto.SeasonUpdates")
	proto1.RegisterType((*FullContext)(nil), "proto.FullContext")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for SeasonUpdate service

type SeasonUpdateClient interface {
	SeasonUpdate(ctx context.Context, in *SeasonUpdates, opts ...grpc.CallOption) (*Empty, error)
}

type seasonUpdateClient struct {
	cc *grpc.ClientConn
}

func NewSeasonUpdateClient(cc *grpc.ClientConn) SeasonUpdateClient {
	return &seasonUpdateClient{cc}
}

func (c *seasonUpdateClient) SeasonUpdate(ctx context.Context, in *SeasonUpdates, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.SeasonUpdate/SeasonUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SeasonUpdate service

type SeasonUpdateServer interface {
	SeasonUpdate(context.Context, *SeasonUpdates) (*Empty, error)
}

func RegisterSeasonUpdateServer(s *grpc.Server, srv SeasonUpdateServer) {
	s.RegisterService(&_SeasonUpdate_serviceDesc, srv)
}

func _SeasonUpdate_SeasonUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeasonUpdates)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeasonUpdateServer).SeasonUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SeasonUpdate/SeasonUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeasonUpdateServer).SeasonUpdate(ctx, req.(*SeasonUpdates))
	}
	return interceptor(ctx, in, info, handler)
}

var _SeasonUpdate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SeasonUpdate",
	HandlerType: (*SeasonUpdateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SeasonUpdate",
			Handler:    _SeasonUpdate_SeasonUpdate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

// Client API for LiveStatUpdate service

type LiveStatUpdateClient interface {
	GetGame(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Empty, error)
	GetStat(ctx context.Context, in *Stat, opts ...grpc.CallOption) (*Empty, error)
}

type liveStatUpdateClient struct {
	cc *grpc.ClientConn
}

func NewLiveStatUpdateClient(cc *grpc.ClientConn) LiveStatUpdateClient {
	return &liveStatUpdateClient{cc}
}

func (c *liveStatUpdateClient) GetGame(ctx context.Context, in *Game, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.LiveStatUpdate/GetGame", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveStatUpdateClient) GetStat(ctx context.Context, in *Stat, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.LiveStatUpdate/GetStat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LiveStatUpdate service

type LiveStatUpdateServer interface {
	GetGame(context.Context, *Game) (*Empty, error)
	GetStat(context.Context, *Stat) (*Empty, error)
}

func RegisterLiveStatUpdateServer(s *grpc.Server, srv LiveStatUpdateServer) {
	s.RegisterService(&_LiveStatUpdate_serviceDesc, srv)
}

func _LiveStatUpdate_GetGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Game)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveStatUpdateServer).GetGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LiveStatUpdate/GetGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveStatUpdateServer).GetGame(ctx, req.(*Game))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiveStatUpdate_GetStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Stat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveStatUpdateServer).GetStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LiveStatUpdate/GetStat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveStatUpdateServer).GetStat(ctx, req.(*Stat))
	}
	return interceptor(ctx, in, info, handler)
}

var _LiveStatUpdate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LiveStatUpdate",
	HandlerType: (*LiveStatUpdateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGame",
			Handler:    _LiveStatUpdate_GetGame_Handler,
		},
		{
			MethodName: "GetStat",
			Handler:    _LiveStatUpdate_GetStat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

// Client API for SeasonContext service

type SeasonContextClient interface {
	GetContext(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FullContext, error)
}

type seasonContextClient struct {
	cc *grpc.ClientConn
}

func NewSeasonContextClient(cc *grpc.ClientConn) SeasonContextClient {
	return &seasonContextClient{cc}
}

func (c *seasonContextClient) GetContext(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FullContext, error) {
	out := new(FullContext)
	err := grpc.Invoke(ctx, "/proto.SeasonContext/GetContext", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SeasonContext service

type SeasonContextServer interface {
	GetContext(context.Context, *Empty) (*FullContext, error)
}

func RegisterSeasonContextServer(s *grpc.Server, srv SeasonContextServer) {
	s.RegisterService(&_SeasonContext_serviceDesc, srv)
}

func _SeasonContext_GetContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeasonContextServer).GetContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SeasonContext/GetContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeasonContextServer).GetContext(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _SeasonContext_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SeasonContext",
	HandlerType: (*SeasonContextServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContext",
			Handler:    _SeasonContext_GetContext_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 554 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x5e, 0x96, 0x9f, 0xae, 0x27, 0x2b, 0x9a, 0xac, 0x09, 0x45, 0x15, 0x82, 0x62, 0x89, 0xb1,
	0x0b, 0x34, 0xa1, 0xc2, 0x0b, 0x20, 0x06, 0xbb, 0xe1, 0x62, 0x4a, 0xe1, 0x06, 0x6e, 0xf0, 0x1a,
	0x6b, 0x44, 0x4a, 0x93, 0x28, 0xf1, 0x26, 0xf6, 0x26, 0xbc, 0x07, 0xaf, 0xc2, 0x03, 0xe1, 0x73,
	0x6c, 0xa7, 0x6e, 0xca, 0x25, 0x57, 0xf1, 0x77, 0xbe, 0xe3, 0xcf, 0x9f, 0xbf, 0xe3, 0x16, 0x66,
	0xeb, 0xa6, 0x56, 0xf2, 0xa7, 0xba, 0x68, 0xbb, 0x46, 0x35, 0x2c, 0xa6, 0x0f, 0x9f, 0x40, 0xfc,
	0x61, 0xd3, 0xaa, 0x07, 0xfe, 0x15, 0xa2, 0xcf, 0x52, 0x6c, 0xd8, 0x29, 0xc4, 0xd5, 0xba, 0x2f,
	0x8b, 0xec, 0x70, 0x11, 0x9c, 0xc7, 0xb9, 0x01, 0xec, 0x31, 0x24, 0x5d, 0xd9, 0x28, 0x5d, 0x0e,
	0xa9, 0x6c, 0x11, 0x63, 0x10, 0xd5, 0x62, 0x23, 0xb3, 0x48, 0x57, 0xa7, 0x39, 0xad, 0xd9, 0x09,
	0x84, 0x4a, 0xdc, 0x66, 0x31, 0x95, 0x70, 0xc9, 0x7f, 0x05, 0x90, 0x5c, 0x57, 0xe2, 0x41, 0x76,
	0xff, 0x41, 0x5e, 0xf7, 0x2a, 0x6d, 0x54, 0xf7, 0xc6, 0xa6, 0xd7, 0x20, 0x36, 0x87, 0xa3, 0xb6,
	0xe9, 0x4b, 0x55, 0x36, 0x75, 0x96, 0x50, 0xff, 0x80, 0x59, 0x06, 0x13, 0x51, 0x14, 0x95, 0xc6,
	0xd9, 0x64, 0x11, 0x6a, 0xca, 0x41, 0xfe, 0x27, 0x80, 0xe8, 0x0a, 0x65, 0xff, 0x6d, 0xec, 0x29,
	0x00, 0x5a, 0xb9, 0xd5, 0x1d, 0xd6, 0xdc, 0x34, 0xf7, 0x2a, 0x6c, 0x01, 0x29, 0xa2, 0x8d, 0x50,
	0xeb, 0x1f, 0xba, 0xc1, 0xf8, 0xf4, 0x4b, 0xec, 0x09, 0x4c, 0x3b, 0x59, 0xec, 0x38, 0xde, 0x16,
	0x50, 0xff, 0xa6, 0xba, 0x93, 0x96, 0x4e, 0x88, 0xf6, 0x2a, 0xb8, 0x1b, 0x4f, 0xea, 0x95, 0xe8,
	0x94, 0xb6, 0x1e, 0x9c, 0x87, 0xf9, 0xb6, 0x80, 0xd7, 0x42, 0x20, 0xeb, 0x22, 0x3b, 0x22, 0xce,
	0x41, 0xce, 0x21, 0x5a, 0x29, 0xa1, 0x30, 0x14, 0x34, 0x43, 0x21, 0x1e, 0x9a, 0x50, 0x1c, 0xe6,
	0x97, 0x30, 0x5d, 0x89, 0x7b, 0x59, 0xd0, 0xd8, 0x9f, 0x41, 0x84, 0x47, 0x66, 0x81, 0x6e, 0x4a,
	0x97, 0xa9, 0x79, 0x24, 0x17, 0x48, 0xe5, 0x44, 0x78, 0xb1, 0x1f, 0xfa, 0xb1, 0xf3, 0x6b, 0x48,
	0x49, 0xc5, 0xce, 0xf7, 0x05, 0x24, 0x2d, 0xad, 0xac, 0xd2, 0xcc, 0x2a, 0x19, 0x3a, 0xb7, 0x24,
	0x0d, 0x8b, 0x56, 0x83, 0xde, 0x80, 0x07, 0x5f, 0x34, 0x16, 0xed, 0x0b, 0xef, 0x34, 0xf2, 0x85,
	0x54, 0x4e, 0x04, 0xfa, 0xb2, 0xd3, 0xb1, 0xbe, 0x0c, 0x1a, 0x54, 0x28, 0x06, 0xad, 0xa2, 0x13,
	0x53, 0x23, 0x15, 0xa4, 0x72, 0x22, 0x50, 0x05, 0xbf, 0x5b, 0x15, 0x83, 0xf8, 0x37, 0x98, 0xad,
	0xa4, 0xe8, 0x9b, 0xfa, 0x4b, 0x5b, 0x08, 0x25, 0x7b, 0xf6, 0x1c, 0x62, 0xbc, 0x78, 0xaf, 0xa5,
	0xc2, 0x71, 0x50, 0x86, 0x61, 0x2f, 0x61, 0x62, 0xee, 0xd2, 0x6b, 0xb1, 0x70, 0x3f, 0x03, 0xc7,
	0xf2, 0xdf, 0x01, 0xa4, 0x1f, 0xef, 0xaa, 0xea, 0xbd, 0xf9, 0x61, 0xb2, 0xb3, 0x5d, 0xed, 0x13,
	0x67, 0xd3, 0x0d, 0xc9, 0x1d, 0xf0, 0x6a, 0x7c, 0x00, 0xf3, 0x3b, 0x47, 0xa7, 0xa0, 0x2a, 0xbd,
	0x18, 0xfd, 0x7a, 0xf7, 0x54, 0x29, 0x47, 0x43, 0x63, 0x1f, 0x5e, 0xba, 0xd7, 0x8f, 0x78, 0xaf,
	0x8f, 0x92, 0x32, 0xf4, 0xf2, 0x12, 0x8e, 0xfd, 0x48, 0xd8, 0xdb, 0x11, 0x3e, 0x75, 0x1b, 0xfd,
	0xdc, 0xe6, 0xc7, 0xb6, 0x6a, 0xfe, 0x6c, 0x0e, 0x96, 0xdf, 0xe1, 0xd1, 0xa7, 0xf2, 0x5e, 0xa2,
	0xb0, 0xdd, 0x77, 0x06, 0x93, 0x2b, 0xa9, 0x68, 0xe8, 0xfe, 0x98, 0xc7, 0x3b, 0x6d, 0x1f, 0x8d,
	0xd5, 0x1f, 0xe4, 0xde, 0x09, 0xef, 0xdc, 0xe8, 0x5c, 0xbc, 0xaf, 0x01, 0xf4, 0x46, 0x87, 0x76,
	0xda, 0xe7, 0x2e, 0x41, 0x6f, 0x1c, 0xfc, 0xe0, 0x26, 0xa1, 0xe2, 0x9b, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x21, 0x11, 0xc2, 0x3b, 0x3b, 0x05, 0x00, 0x00,
}
