CREATE DATABASE lcs DEFAULT CHARACTER SET = utf8;

use lcs;

CREATE TABLE players (
	playerid INTEGER AUTO_INCREMENT PRIMARY KEY;
	lcsid INTEGER NOT NULL;
	riotid INTEGER NOT NULL;
	name VARCHAR(40) NOT NULL;
	teamid INTEGER NOT NULL;
	FOREIGN KEY (`teamid`) REFERENCES teams(`teamid`);
) ENGINE = InnoDB;

CREATE TABLE teams (
	teamid INTEGER AUTO_INCREMENT PRIMARY KEY;
	lcsid INTEGER NOT NULL;
	riotid INTEGER NOT NULL;
	name VARCHAR(40) NOT NULL;
	tag VARCHAR(10) NOT NULL;
) ENGINE = InnoDB;

CREATE TABLE games (
	gameid INTEGER AUTO_INCREMENT PRIMARY KEY;
	lcsgameid VARCHAR(20) NOT NULL;
	lcsmatchid VARCHAR(20) NOT NULL;
	redteam INTEGER NOT NULL;
	blueteam INTEGER NOT NULL;
	gamestart DATETIME NOT NULL;
	gameend DATETIME DEFAULT NULL;
) ENGINE = InnoDB;
