// Code generated by protoc-gen-go.
// source: new.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	new.proto

It has these top-level messages:
	Empty
	Team
	Teams
	Player
	Players
	Game
	Games
	Stat
	Stats
	SeasonUpdates
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Team struct {
	Lcsid  int32  `protobuf:"varint,2,opt,name=lcsid" json:"lcsid,omitempty"`
	Riotid int32  `protobuf:"varint,3,opt,name=riotid" json:"riotid,omitempty"`
	Name   string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Tag    string `protobuf:"bytes,5,opt,name=tag" json:"tag,omitempty"`
}

func (m *Team) Reset()                    { *m = Team{} }
func (m *Team) String() string            { return proto1.CompactTextString(m) }
func (*Team) ProtoMessage()               {}
func (*Team) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Teams struct {
	Teams []*Team `protobuf:"bytes,1,rep,name=teams" json:"teams,omitempty"`
}

func (m *Teams) Reset()                    { *m = Teams{} }
func (m *Teams) String() string            { return proto1.CompactTextString(m) }
func (*Teams) ProtoMessage()               {}
func (*Teams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Teams) GetTeams() []*Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

type Player struct {
	Lcsid  int32  `protobuf:"varint,2,opt,name=lcsid" json:"lcsid,omitempty"`
	Riotid int32  `protobuf:"varint,3,opt,name=riotid" json:"riotid,omitempty"`
	Name   string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Teamid int32  `protobuf:"varint,5,opt,name=teamid" json:"teamid,omitempty"`
}

func (m *Player) Reset()                    { *m = Player{} }
func (m *Player) String() string            { return proto1.CompactTextString(m) }
func (*Player) ProtoMessage()               {}
func (*Player) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Players struct {
	Players []*Player `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
}

func (m *Players) Reset()                    { *m = Players{} }
func (m *Players) String() string            { return proto1.CompactTextString(m) }
func (*Players) ProtoMessage()               {}
func (*Players) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Players) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type Game struct {
	Lcsid       int32  `protobuf:"varint,2,opt,name=lcsid" json:"lcsid,omitempty"`
	Riotgameid  string `protobuf:"bytes,3,opt,name=riotgameid" json:"riotgameid,omitempty"`
	Riotmatchid string `protobuf:"bytes,4,opt,name=riotmatchid" json:"riotmatchid,omitempty"`
	Redteamid   int32  `protobuf:"varint,5,opt,name=redteamid" json:"redteamid,omitempty"`
	Blueteamid  int32  `protobuf:"varint,6,opt,name=blueteamid" json:"blueteamid,omitempty"`
	Gamestart   int64  `protobuf:"varint,7,opt,name=gamestart" json:"gamestart,omitempty"`
	Gameend     int64  `protobuf:"varint,8,opt,name=gameend" json:"gameend,omitempty"`
}

func (m *Game) Reset()                    { *m = Game{} }
func (m *Game) String() string            { return proto1.CompactTextString(m) }
func (*Game) ProtoMessage()               {}
func (*Game) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Games struct {
	Games []*Game `protobuf:"bytes,1,rep,name=games" json:"games,omitempty"`
}

func (m *Games) Reset()                    { *m = Games{} }
func (m *Games) String() string            { return proto1.CompactTextString(m) }
func (*Games) ProtoMessage()               {}
func (*Games) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Games) GetGames() []*Game {
	if m != nil {
		return m.Games
	}
	return nil
}

type Stat struct {
	Riotname string `protobuf:"bytes,2,opt,name=riotname" json:"riotname,omitempty"`
}

func (m *Stat) Reset()                    { *m = Stat{} }
func (m *Stat) String() string            { return proto1.CompactTextString(m) }
func (*Stat) ProtoMessage()               {}
func (*Stat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Stats struct {
	Stats []*Stat `protobuf:"bytes,1,rep,name=stats" json:"stats,omitempty"`
}

func (m *Stats) Reset()                    { *m = Stats{} }
func (m *Stats) String() string            { return proto1.CompactTextString(m) }
func (*Stats) ProtoMessage()               {}
func (*Stats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Stats) GetStats() []*Stat {
	if m != nil {
		return m.Stats
	}
	return nil
}

type SeasonUpdates struct {
	TeamsCreate   *Teams   `protobuf:"bytes,1,opt,name=teamsCreate" json:"teamsCreate,omitempty"`
	TeamsUpdate   *Teams   `protobuf:"bytes,2,opt,name=teamsUpdate" json:"teamsUpdate,omitempty"`
	PlayersCreate *Players `protobuf:"bytes,3,opt,name=playersCreate" json:"playersCreate,omitempty"`
	PlayersUpdate *Players `protobuf:"bytes,4,opt,name=playersUpdate" json:"playersUpdate,omitempty"`
}

func (m *SeasonUpdates) Reset()                    { *m = SeasonUpdates{} }
func (m *SeasonUpdates) String() string            { return proto1.CompactTextString(m) }
func (*SeasonUpdates) ProtoMessage()               {}
func (*SeasonUpdates) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SeasonUpdates) GetTeamsCreate() *Teams {
	if m != nil {
		return m.TeamsCreate
	}
	return nil
}

func (m *SeasonUpdates) GetTeamsUpdate() *Teams {
	if m != nil {
		return m.TeamsUpdate
	}
	return nil
}

func (m *SeasonUpdates) GetPlayersCreate() *Players {
	if m != nil {
		return m.PlayersCreate
	}
	return nil
}

func (m *SeasonUpdates) GetPlayersUpdate() *Players {
	if m != nil {
		return m.PlayersUpdate
	}
	return nil
}

func init() {
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
	proto1.RegisterType((*Team)(nil), "proto.Team")
	proto1.RegisterType((*Teams)(nil), "proto.Teams")
	proto1.RegisterType((*Player)(nil), "proto.Player")
	proto1.RegisterType((*Players)(nil), "proto.Players")
	proto1.RegisterType((*Game)(nil), "proto.Game")
	proto1.RegisterType((*Games)(nil), "proto.Games")
	proto1.RegisterType((*Stat)(nil), "proto.Stat")
	proto1.RegisterType((*Stats)(nil), "proto.Stats")
	proto1.RegisterType((*SeasonUpdates)(nil), "proto.SeasonUpdates")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for ContextUpdate service

type ContextUpdateClient interface {
	SeasonUpdate(ctx context.Context, in *SeasonUpdates, opts ...grpc.CallOption) (*Empty, error)
}

type contextUpdateClient struct {
	cc *grpc.ClientConn
}

func NewContextUpdateClient(cc *grpc.ClientConn) ContextUpdateClient {
	return &contextUpdateClient{cc}
}

func (c *contextUpdateClient) SeasonUpdate(ctx context.Context, in *SeasonUpdates, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.ContextUpdate/SeasonUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ContextUpdate service

type ContextUpdateServer interface {
	SeasonUpdate(context.Context, *SeasonUpdates) (*Empty, error)
}

func RegisterContextUpdateServer(s *grpc.Server, srv ContextUpdateServer) {
	s.RegisterService(&_ContextUpdate_serviceDesc, srv)
}

func _ContextUpdate_SeasonUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeasonUpdates)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextUpdateServer).SeasonUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ContextUpdate/SeasonUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextUpdateServer).SeasonUpdate(ctx, req.(*SeasonUpdates))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContextUpdate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ContextUpdate",
	HandlerType: (*ContextUpdateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SeasonUpdate",
			Handler:    _ContextUpdate_SeasonUpdate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x26, 0x9b, 0x38, 0xd9, 0x4c, 0x36, 0x08, 0x59, 0x15, 0x8a, 0x2a, 0x84, 0x8a, 0x2f, 0x54,
	0x1c, 0x7a, 0x28, 0xbc, 0x41, 0x55, 0x71, 0x45, 0x2e, 0x5c, 0xb8, 0xb9, 0x8d, 0x55, 0x2a, 0x35,
	0x3f, 0x8a, 0x8d, 0xa0, 0xef, 0xc9, 0x8d, 0x97, 0xc1, 0x63, 0x3b, 0xad, 0x5b, 0x55, 0x9c, 0xf6,
	0x54, 0x7f, 0x3f, 0x33, 0xf3, 0xd9, 0x93, 0x42, 0xde, 0xca, 0x5f, 0x8b, 0x7e, 0xe8, 0x74, 0x47,
	0x89, 0xfd, 0x61, 0x19, 0x90, 0x75, 0xd3, 0xeb, 0x13, 0xfb, 0x0e, 0xc9, 0x57, 0x29, 0x1a, 0x3a,
	0x01, 0x72, 0xdc, 0xa9, 0x43, 0x5d, 0x3d, 0xcc, 0xa2, 0x39, 0xe1, 0x0e, 0xd0, 0xd7, 0x90, 0x0e,
	0x87, 0x4e, 0x1b, 0x3a, 0xb6, 0xb4, 0x47, 0x94, 0x42, 0xd2, 0x8a, 0x46, 0x56, 0x89, 0x61, 0x73,
	0x6e, 0xcf, 0xf4, 0x15, 0xc4, 0x5a, 0xec, 0x2b, 0x62, 0x29, 0x3c, 0xb2, 0x0f, 0x40, 0xb0, 0xb7,
	0xa2, 0xef, 0x80, 0x68, 0x3c, 0x54, 0xd1, 0x2c, 0x9e, 0x17, 0xcb, 0xc2, 0x65, 0x59, 0xa0, 0xc8,
	0x9d, 0xc2, 0xb6, 0x90, 0x7e, 0x39, 0x8a, 0x93, 0x1c, 0x9e, 0x21, 0x89, 0xf1, 0x62, 0x53, 0xe3,
	0x25, 0xce, 0xeb, 0x10, 0x5b, 0x42, 0xe6, 0x66, 0x28, 0xfa, 0x1e, 0xb2, 0xde, 0x1d, 0x7d, 0xa6,
	0xd2, 0x67, 0x72, 0x06, 0x3e, 0xaa, 0xec, 0x4f, 0x04, 0xc9, 0x67, 0x6c, 0x7a, 0x3f, 0xd6, 0x5b,
	0x00, 0x0c, 0xb2, 0x37, 0x0e, 0x1f, 0x2d, 0xe7, 0x01, 0x43, 0x67, 0x50, 0x20, 0x6a, 0x84, 0xde,
	0xfd, 0x30, 0x06, 0x97, 0x32, 0xa4, 0xe8, 0x1b, 0xc8, 0x07, 0x59, 0x5f, 0xe5, 0xbd, 0x10, 0xd8,
	0x7f, 0x7b, 0xfc, 0x29, 0xbd, 0x9c, 0x5a, 0x39, 0x60, 0xb0, 0x1a, 0x27, 0x29, 0x2d, 0x06, 0x5d,
	0x65, 0x46, 0x8e, 0xf9, 0x85, 0xa0, 0x15, 0x64, 0x08, 0x64, 0x5b, 0x57, 0x8f, 0x56, 0x1b, 0x21,
	0xae, 0x06, 0x6f, 0x65, 0x57, 0x63, 0xfd, 0x37, 0xab, 0x41, 0x91, 0x3b, 0x85, 0x31, 0x48, 0x36,
	0x5a, 0x68, 0x3a, 0x85, 0x47, 0x0c, 0x6e, 0x9f, 0xfb, 0xc1, 0x5e, 0xe4, 0x8c, 0xb1, 0x1f, 0x7a,
	0x6c, 0x3f, 0x85, 0x87, 0x9b, 0x7e, 0x28, 0x72, 0xa7, 0xb0, 0xbf, 0x11, 0x94, 0x1b, 0x29, 0x54,
	0xd7, 0x7e, 0xeb, 0x6b, 0xa1, 0x4d, 0x88, 0x05, 0x14, 0xf6, 0x2b, 0x58, 0x0d, 0xd2, 0x60, 0x53,
	0x1a, 0x99, 0xd2, 0xa7, 0xe0, 0x2b, 0x51, 0x3c, 0x34, 0x9c, 0xfd, 0xae, 0xde, 0x86, 0xb9, 0xef,
	0x77, 0x06, 0xfa, 0x09, 0x4a, 0xbf, 0x4f, 0x3f, 0x21, 0xb6, 0x15, 0x2f, 0xaf, 0x76, 0xae, 0xf8,
	0xb5, 0x29, 0xa8, 0xf2, 0x73, 0x92, 0xff, 0x56, 0x39, 0xd3, 0x72, 0x0d, 0xe5, 0xaa, 0x6b, 0xb5,
	0xfc, 0xad, 0xcf, 0xc3, 0x9f, 0xc2, 0xdb, 0xd2, 0xc9, 0xf8, 0x24, 0xe1, 0x13, 0x4c, 0xc7, 0xf4,
	0xee, 0x5f, 0xf9, 0x62, 0x9b, 0x5a, 0xf8, 0xf1, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x99,
	0x74, 0x43, 0xbb, 0x03, 0x00, 0x00,
}
